### ISSUE TITLE
使用GCM-FOR-mojo,在使用gcm.sh脚本时如何同时安装QQ和微信

### ISSUE THREAD

**Issue by MasterOfStar** [null-ecp/FFM-one-step#1]
使用GCM-FOR-mojo,在使用gcm.sh脚本时如何同时安装QQ和微信
走mipush渠道

**Comment by null-ecp** [comment]
在重新走一次脚本即可，可以用nohup守护进程，或者使用screen，ctrl+a+d来放进后台。
